# fly.toml app configuration file generated for openai-cpa-8zzojq on 2026-04-20T15:32:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openai-cpa-8zzojq'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
